# Generated by Django 5.0 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=4.5)),
                ('featured', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
